Repository WebDevStudios/wd_s, pull requests merged in 2018-09, with the labels that each got.

#381 Hotfix/#380 color picker swatches
  assets/scripts/admin-acf.js
  assets/scripts/admin-acf.min.js
Labels: bug, r4r

#388 PHPCS Warnings and Error Fixes
  functions.php
  inc/acf.php
  inc/scaffolding.php
  inc/scripts.php
  template-parts/scaffolding/scaffolding-globals.php
Labels: r4r

#390 Hotfix/#387 css lint fixes
  .sass-lint.yml
  assets/sass/modules/navigation/_main-navigation.scss
  style.css
Labels: bug, r4r

#392 Fixes JS lint errors
  assets/scripts/customizer.js
  assets/scripts/scaffolding.js
Labels: bug, r4r

#393 Adds filters to search post meta using default WP search
  functions.php
  inc/acf-search.php
Labels: r4r

#396 Updates ACF Block Defaults
  acf-json/group_594168e970d85.json
  assets/sass/base/_media.scss
  assets/sass/modules/content-blocks/_global.scss
  inc/acf.php
  style.css
  style.min.css
Labels: r4r

#395 Replaces the <button> with an <input> to submit search results form
  searchform.php
Labels: r4r, returned
