Repository WebDevStudios/wd_s, pull requests merged in 2018-10, with the labels that each got.

#398 Theme/#397 og meta tags
  inc/hooks.php
Labels: enhancement, hacktoberfest, r4r

#400 Hotfix/#399 attribute spacing
  inc/acf.php
  template-parts/content-blocks/block-cta.php
  template-parts/content-blocks/block-fifty_media_text.php
  template-parts/content-blocks/block-fifty_text_media.php
  template-parts/content-blocks/block-fifty_text_only.php
  template-parts/content-blocks/block-generic_content.php
  template-parts/content-blocks/block-hero.php
  template-parts/content-blocks/block-recent_posts.php
  template-parts/content-blocks/block-related_posts.php
Labels: bug, hacktoberfest, r4r

#404 Replaces return with continue in expiration check
  inc/acf.php
Labels: bug, hacktoberfest, r4r

#410 Theme/menu refinements
  footer.php
  header.php
  inc/template-tags.php
Labels: enhancement, hacktoberfest, r4r

#407 Theme/move external css files
  assets/sass/style.scss
  assets/sass/vendor/animate/_animate.scss
  assets/sass/vendor/normalize/_normalize.scss
  style.css
  style.min.css
Labels: enhancement, hacktoberfest, r4r

#411 Theme/general theme enhancements
  archive.php
  assets/sass/base/_links.scss
  assets/sass/modules/_buttons.scss
  assets/sass/modules/_comments.scss
  assets/sass/utilities/variables/_transitions.scss
  inc/hooks.php
  inc/template-tags.php
  index.php
  search.php
  style.css
  style.min.css
  template-parts/content-blocks/block-cta.php
Labels: enhancement, hacktoberfest, r4r

#409 Theme/#408 remove inline styles
  acf-json/group_58ebcc07bfbd7.json
  acf-json/group_594168e970d85.json
  acf-json/group_5bb7934b61627.json
  admin-acf-styles.css
  assets/sass/base/_media.scss
  assets/scripts/admin-acf.js
  assets/scripts/admin-acf.min.js
  inc/acf.php
  inc/extras.php
  style.css
  style.min.css
  template-parts/content-blocks/block-hero.php
Labels: enhancement, hacktoberfest, r4r

#418 Theme/#415 remove google+
  assets/images/svg-icons.svg
  assets/images/svg-icons/_IcoMoon.json
  assets/images/svg-icons/googleplus-square.svg
  assets/sass/utilities/variables/_colors.scss
  inc/customizer/settings.php
  inc/template-tags.php
  languages/_s.pot
  style.css
  style.min.css
Labels: r4r

#428 fixes typo, updated documentation to reflect function, and changes at…
  inc/acf.php
Labels: bug, r4r

#420 Removes the panel removal of Nav Menus and Widgets
  inc/customizer/customizer.php
Labels: hacktoberfest, r4r
