Repository WebDevStudios/wd_s, pull requests merged in 2019-10, with the labels that each got.

#489 Hotfix/theme cleanup
  404.php
  inc/acf.php
  inc/customizer/settings.php
  template-parts/scaffolding/scaffolding-elements.php
  template-parts/scaffolding/scaffolding-typography.php
Labels: bug, hacktoberfest, r4r

#488 Hotfix/mobile js issues
  assets/scripts/concat/accordion.js
  assets/scripts/concat/header-button.js
  assets/scripts/concat/modal.js
  assets/scripts/project.js
  assets/scripts/project.min.js
  style.css
  style.min.css
Labels: bug, hacktoberfest, r4r

#487 Adds unique identifiers to form labels and inputs
  searchform.php
Labels: hacktoberfest, r4r

#496 Fixes PHPCS error.
  functions.php
Labels: hacktoberfest, r4r

#493 Sf/node version info 491
  .nvmrc
  README.md
Labels: bug, hacktoberfest

#499 Adjust size/position of checked border to fix the ‘broken’ look
  assets/sass/modules/_forms.scss
  gutenberg-blocks-style.css
  style.css
  style.min.css
Labels: r4r

#490 Feature/chrome lazyload
  inc/hooks.php
  inc/template-tags.php
  template-parts/content-blocks/block-wds-fifty-media-text.php
  template-parts/content-blocks/block-wds-fifty-text-media.php
  template-parts/content-blocks/block-wds-recent-posts.php
  template-parts/content-blocks/block-wds-related-posts.php
Labels: enhancement, hacktoberfest, r4r

#502 Updates the broken screenshot in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, hacktoberfest, r4r
