Repository WebDevStudios/wd_s, pull requests merged in 2019-11, with the labels that each got.

#501 Feature/#500 video embeds
  assets/sass/base/_media.scss
  gutenberg-blocks-style.css
  style.css
  style.min.css
Labels: enhancement, hacktoberfest, r4r

#504 Hotfix/#503 default button colors
  assets/sass/base/_links.scss
  assets/sass/modules/wp-blocks/default-blocks/_wp-block-button.scss
  assets/sass/utilities/mixins/_color-classes.scss
  gutenberg-blocks-style.css
  style.css
  style.min.css
Labels: r4r

#505 Hotfix/date field bug
  acf-json/group_594168e970d85.json
  inc/acf-gutenberg.php
  inc/acf.php
Labels: bug, documentation, r4r

#494 Adds a default icon for the Accordion block
  inc/acf-gutenberg.php
Labels: hacktoberfest, r4r
