Repository WebDevStudios/wd_s, pull requests merged in 2022-05, with the labels that each got.

#787 Fixes an issue where not all partials are imported
  src/scss/global/index.scss
  src/scss/index.scss
Labels: bug, r4r

#789 Adds fonts back to copyplugin
  webpack.config.js
Labels: bug, r4r

#744 Critical CSS
  inc/scripts.php
  src/critical.js
  src/index.js
  src/scss/critical.scss
  src/scss/critical/_header.scss
  src/scss/critical/_menus.scss
  src/scss/critical/_mobile-menus.scss
  src/scss/critical/index.scss
  src/scss/template-tags/index.scss
  src/scss/templates/index.scss
  webpack.config.js
Labels: r4r, enhancement

#858 Bumps to Tailwind 3.0.24
  package-lock.json
  package.json
  tailwind.config.js
Labels: r4r

#862 Bump WP Scripts version
  .github/workflows/codeql-analysis.yml
  .stylelintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/scss/blocks/core/_gallery.scss
  src/scss/blocks/core/_image.scss
  src/scss/blocks/core/_list.scss
  src/scss/blocks/core/_table.scss
  src/scss/blocks/core/index.scss
  src/scss/blocks/index.scss
  src/scss/critical.scss
  src/scss/critical/_header.scss
  src/scss/critical/_menus.scss
  src/scss/critical/_mobile-menus.scss
  src/scss/critical/index.scss
  src/scss/index.scss
  src/scss/template-tags/_forms.scss
  src/scss/template-tags/_modals.scss
  src/scss/template-tags/_off-canvas.scss
  src/scss/template-tags/index.scss
  src/scss/templates/_comments.scss
  src/scss/templates/_footer.scss
  src/scss/templates/_posts.scss
  src/scss/templates/index.scss
  src/scss/wordpress-global/index.scss
Labels: r4r, dependencies

#798 Feature/#747 Scafffolding Template
  inc/scaffolding.php
  src/scss/global/_global.scss
  src/scss/templates/_scaffolding.scss
  src/scss/templates/index.scss
  src/scss/wordpress-global/_alignment.scss
  tailwind.config.js
  template-parts/scaffolding/scaffolding-blank.php
  template-parts/scaffolding/scaffolding-buttons.php
  template-parts/scaffolding/scaffolding-elements.php
  template-parts/scaffolding/scaffolding-forms.php
  template-parts/scaffolding/scaffolding-globals.php
  template-parts/scaffolding/scaffolding-icons.php
  template-parts/scaffolding/scaffolding-media.php
  template-parts/scaffolding/scaffolding-typography.php
  template-scaffolding.php
Labels: r4r, enhancement
